* Introduction

  It really started with a [[https://skillsmatter.com/skillscasts/3537-lightening-talk-literate-programming-with-clojure-and-org-babel][magical talk]] by [[https://twitter.com/magic_bloat][Andrew Cowper]] on literate
  programming with org-mode and clojure.

  I was then inspired by [[https://github.com/t-ob/dotfiles][Tom O'Brien's dotfiles]] to do a org-mode
  version of my emacs config. I also completely broke my emacs config
  trying to do some other things and I figured I should fix it
  properly rather than just getting the basics back together.

  I've since moved over to using use-package. That experiment was in
  straight elisp though. Now I'm trying to merge this literate style
  with that safer start up and package pinning.

  The real content is in [[./org/config.org][config.org]], which would probably be more
  interesting to read.

  I used to have some things here to make stuff work on mac osx, but
  I've been all in on GNU/Linux for a while now (Ubuntu 18.04 at the
  time of this commit), so I'm not sure I can guarantee that any macos
  things will work any more.

  If you want to use this I suggest you do the following:

  - create a emacs-config directory in your $HOME dir.
  - clone this repo in that directory
  - do a symbolic link from the clone to your .emacs.d directory

  This is what I normally do. This lets me clone or create lots of new
  emacs configurations without trashing any of the earlier ones and
  lets me try a lot of things out. It seems to be working for me so
  far.
