* Introduction

  I was inspired by [[https://github.com/t-ob/dotfiles][Tom O'Brien's dotfiles]] to do a org-mode version of
  my emacs config. I also completely broke my emacs config trying to
  do some other things and I figured I should fix it properly rather
  than just getting the basics back together.

  The real content is in [[./org/config.org][config.org]], which would probably be more
  interesting to read.

  This emacs config was set up to run on Mac OS X using the emacs from
  the very good [[http://emacsformacosx.com/][emacsformacosx.com]]. I've not made it multi OS yet, and
  a lot of the things solve problems that really only occur on a UK
  Mac (things like the # key).

  If you want to use this I suggest you do the following:

  - create a emacs-config directory in your $HOME dir.
  - clone this repo in that directory
  - do a symbolic link from the clone to your .emacs.d directory
    
  This is what I normally do. This lets me clone or create lots of new
  emacs configurations without trashing any of the earlier ones and
  lets me try a lot of things out. It seems to be working for me so
  far.
