* Introduction

  It really started with a [[https://skillsmatter.com/skillscasts/3537-lightening-talk-literate-programming-with-clojure-and-org-babel][magical talk]] by [[https://twitter.com/magic_bloat][Andrew Cowper]] on literate
  programming with org-mode and clojure.

  I was then inspired by [[https://github.com/t-ob/dotfiles][Tom O'Brien's dotfiles]] to do a org-mode
  version of my emacs config. I also completely broke my emacs config
  trying to do some other things and I figured I should fix it
  properly rather than just getting the basics back together.

  The real content is in [[./org/config.org][config.org]], which would probably be more
  interesting to read.

  This emacs config was set up to run on Mac OS X using the emacs from
  the very good [[http://emacsformacosx.com/][emacsformacosx.com]]. I've not made it multi OS yet, and
  a lot of the things solve problems that really only occur on a UK
  Mac (things like the # key).

  If you want to use this I suggest you do the following:

  - create a emacs-config directory in your $HOME dir.
  - clone this repo in that directory
  - do a symbolic link from the clone to your .emacs.d directory
    
  This is what I normally do. This lets me clone or create lots of new
  emacs configurations without trashing any of the earlier ones and
  lets me try a lot of things out. It seems to be working for me so
  far.

* Features

  Here are the things this emacs config gives examples for:

  - clojure support with cider
  - Separating custom.el from the rest of your files.
  - hippie expand
  - upcasing and downcasing
  - Using diminish to clean up a mode-line
  - Adding non-elpa files
  - Using multiple elpa package archives
  - Using color themes and custom fonts
  - removing chrome from the windows
  - very basic helm mode setup
  - a basic ido setup for somethings
  - magit & git gutter mode
  - using Emacs as a twitter client
  - using Emacs as a gtalk/jabber client
  - using Emacs as an irc client
  - paredit and rainbow delimiters
  - using add-hook
  - org-mode with some custom agendas and sorting
  - emacs on Mac OS X fixes (vestigial now)
