* non-elpa files

  Unfortunately, we can't get everything we want from the package
  archives or we might have files that we're working on locally that
  we haven't released yet. We keep those in a non-elpa directory. We
  need to add this to the load-path so that we can require the files
  we have here.

  #+BEGIN_SRC emacs-lisp
    (add-to-list 'load-path "~/.emacs.d/non-elpa/")
  #+END_SRC

* Macintosh Specific Setup

** # is broken on UK Macs

   On UK keyboards shift-3 is bound to £. This is a real pain. The #
   character is usually bound to M-3. This also causes problems,
   especially with things like window-number modes. We have a hacked
   window-number mode below that maps window 3 to s-3, which solves
   that problem. The # problem is solved with this bit of code below.
   
   #+BEGIN_SRC emacs-lisp
     (global-set-key (kbd "M-3") '(lambda () (interactive) (insert "#")))
   #+END_SRC

   We also need to deal with £ being a UTF-8 character so we don't get
   annoying Â characters before non-ascii characters.

   #+BEGIN_SRC emacs-lisp
     (setq default-process-coding-system '(utf-8-unix . utf-8-unix))
   #+END_SRC
   
* helm-mode

  helm-mode is the succesor to anything.el. I don't really have my
  head around it all yet, but I'm already pretty impressed with it so
  I'll include it here and add more to it as I understand what is
  going on.

  My helm-mode guru is Kris Jenkins [[http://twitter.com/krisajenkins][@krisajenkins]].
  
  #+BEGIN_SRC emacs-lisp
    (maybe-install-and-require 'helm)
    (helm-mode 1)
  #+END_SRC
  
* git

  magit is a *fantastic* mode for dealing with git.

  #+BEGIN_SRC emacs-lisp
    (maybe-install-and-require 'magit)
  #+END_SRC
